# configuration file for Weston

[core]
require-input=false

[launcher]
icon=/usr/share/weston/icon_terminal.png
path=/usr/bin/weston-terminal

[launcher]
icon=/usr/share/icons/icon_jssrec.png
path=/usr/bin/jssRecovery

